// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class BaoCao
{
    public int MaBaoCao { get; set; }

    public string? LoaiBaoCao { get; set; }

    public DateOnly? NgayBaoCao { get; set; }

    public string? NoiDung { get; set; }

    public int? MaNguoiDung { get; set; }

    public virtual NguoiDung? MaNguoiDungNavigation { get; set; }
}