// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class BaoCaoThienTai
{
    public int MaBaoCaoThienTai { get; set; }

    public string TieuDe { get; set; } = null!;

    public string LoaiThienTai { get; set; } = null!;

    public int? MaTruotLo { get; set; }

    public int? MaLuQuet { get; set; }

    public int? MaXa { get; set; }

    public DateOnly NgayBaoCao { get; set; }

    public string? NoiDung { get; set; }

    public int? MaNguoiTao { get; set; }

    public int? MaTrangThai { get; set; }

    public DateTime? NgayCapNhat { get; set; }

    public virtual DiemLuQuet? MaLuQuetNavigation { get; set; }

    public virtual NguoiDung? MaNguoiTaoNavigation { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }

    public virtual DiemTruotLo? MaTruotLoNavigation { get; set; }

    public virtual DonViHanhChinhXa? MaXaNavigation { get; set; }
}