// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class DiemLuQuet
{
    public int MaLuQuet { get; set; }

    public string TenDiem { get; set; } = null!;

    public string? ToaDo { get; set; }

    public int? MaXa { get; set; }

    public DateOnly? NgayXayRa { get; set; }

    public string? MucDoNghiemTrong { get; set; }

    public string? NguyenNhan { get; set; }

    public string? ThietHai { get; set; }

    public int? MaTrangThai { get; set; }

    public int? MaNguoiCapNhat { get; set; }

    public DateTime? NgayCapNhat { get; set; }

    public virtual ICollection<BaoCaoThienTai> BaoCaoThienTai { get; set; } = new List<BaoCaoThienTai>();

    public virtual NguoiDung? MaNguoiCapNhatNavigation { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }

    public virtual DonViHanhChinhXa? MaXaNavigation { get; set; }
}