// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class DienTichChuaCoRung
{
    public int MaChuaCoRung { get; set; }

    public int? MaLoDat { get; set; }

    public decimal DienTich { get; set; }

    public int? MaLapDia { get; set; }

    public string? KeHoachTrongRung { get; set; }

    public virtual DieuKienLapDia? MaLapDiaNavigation { get; set; }

    public virtual LoDatRung? MaLoDatNavigation { get; set; }
}