// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class DieuKienLapDia
{
    public int MaLapDia { get; set; }

    public string? LoaiDat { get; set; }

    public decimal? DoDoc { get; set; }

    public decimal? DoAm { get; set; }

    public string? KhiHau { get; set; }

    public string? MoTa { get; set; }

    public virtual ICollection<DienTichChuaCoRung> DienTichChuaCoRung { get; set; } = new List<DienTichChuaCoRung>();

    public virtual ICollection<KhuRung> KhuRung { get; set; } = new List<KhuRung>();

    public virtual ICollection<LoDatRung> LoDatRung { get; set; } = new List<LoDatRung>();
}