// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class DonViHanhChinhTinh
{
    public int MaTinh { get; set; }

    public string TenTinh { get; set; } = null!;

    public virtual ICollection<DonViHanhChinhHuyen> DonViHanhChinhHuyen { get; set; } = new List<DonViHanhChinhHuyen>();
}