// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class DonViHanhChinhHuyen
{
    public int MaHuyen { get; set; }

    public string TenHuyen { get; set; } = null!;

    public int? MaTinh { get; set; }

    public virtual ICollection<DonViHanhChinhXa> DonViHanhChinhXa { get; set; } = new List<DonViHanhChinhXa>();

    public virtual DonViHanhChinhTinh? MaTinhNavigation { get; set; }
}