// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ForestManagementSystem.Models;

public partial class ForestManagementSystemContext : DbContext
{
    public ForestManagementSystemContext(DbContextOptions<ForestManagementSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BaoCao> BaoCao { get; set; }

    public virtual DbSet<BienDongRung> BienDongRung { get; set; }

    public virtual DbSet<DienTichChuaCoRung> DienTichChuaCoRung { get; set; }

    public virtual DbSet<DieuKienLapDia> DieuKienLapDia { get; set; }

    public virtual DbSet<DonViHanhChinhHuyen> DonViHanhChinhHuyen { get; set; }

    public virtual DbSet<DonViHanhChinhTinh> DonViHanhChinhTinh { get; set; }

    public virtual DbSet<DonViHanhChinhXa> DonViHanhChinhXa { get; set; }

    public virtual DbSet<HuongDanSuDung> HuongDanSuDung { get; set; }

    public virtual DbSet<KhuRung> KhuRung { get; set; }

    public virtual DbSet<LichSuTacDong> LichSuTacDong { get; set; }

    public virtual DbSet<LichSuTruyCap> LichSuTruyCap { get; set; }

    public virtual DbSet<LoDatRung> LoDatRung { get; set; }

    public virtual DbSet<LoaiCay> LoaiCay { get; set; }

    public virtual DbSet<LoaiRung> LoaiRung { get; set; }

    public virtual DbSet<Menu> Menu { get; set; }

    public virtual DbSet<NguoiDung> NguoiDung { get; set; }

    public virtual DbSet<NguoiDung_Nhom> NguoiDung_Nhom { get; set; }

    public virtual DbSet<NguonGocRung> NguonGocRung { get; set; }

    public virtual DbSet<NhomNguoiDung> NhomNguoiDung { get; set; }

    public virtual DbSet<PhanQuyenNguoiDung> PhanQuyenNguoiDung { get; set; }

    public virtual DbSet<PhanQuyenNhom> PhanQuyenNhom { get; set; }

    public virtual DbSet<TrangThai> TrangThai { get; set; }

    public virtual DbSet<TruLuong> TruLuong { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BaoCao>(entity =>
        {
            entity.HasKey(e => e.MaBaoCao).HasName("PK__BaoCao__25A9188CB0DD52CA");

            entity.Property(e => e.LoaiBaoCao)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NoiDung).HasColumnType("text");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.BaoCao)
                .HasForeignKey(d => d.MaNguoiDung)
                .HasConstraintName("FK__BaoCao__MaNguoiD__60A75C0F");
        });

        modelBuilder.Entity<BienDongRung>(entity =>
        {
            entity.HasKey(e => e.MaBienDong).HasName("PK__BienDong__1BB1521FCCAE3C37");

            entity.Property(e => e.DienTichBienDong).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LoaiBienDong)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MoTa).HasColumnType("text");

            entity.HasOne(d => d.MaLoDatNavigation).WithMany(p => p.BienDongRung)
                .HasForeignKey(d => d.MaLoDat)
                .HasConstraintName("FK__BienDongR__MaLoD__75A278F5");
        });

        modelBuilder.Entity<DienTichChuaCoRung>(entity =>
        {
            entity.HasKey(e => e.MaChuaCoRung).HasName("PK__DienTich__5B3E3D35B80F5A9F");

            entity.Property(e => e.DienTich).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.KeHoachTrongRung).HasColumnType("text");

            entity.HasOne(d => d.MaLapDiaNavigation).WithMany(p => p.DienTichChuaCoRung)
                .HasForeignKey(d => d.MaLapDia)
                .HasConstraintName("FK__DienTichC__MaLap__797309D9");

            entity.HasOne(d => d.MaLoDatNavigation).WithMany(p => p.DienTichChuaCoRung)
                .HasForeignKey(d => d.MaLoDat)
                .HasConstraintName("FK__DienTichC__MaLoD__787EE5A0");
        });

        modelBuilder.Entity<DieuKienLapDia>(entity =>
        {
            entity.HasKey(e => e.MaLapDia).HasName("PK__DieuKien__3E46A489A80CCD7B");

            entity.Property(e => e.DoAm).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.DoDoc).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.KhiHau)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LoaiDat)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MoTa).HasColumnType("text");
        });

        modelBuilder.Entity<DonViHanhChinhHuyen>(entity =>
        {
            entity.HasKey(e => e.MaHuyen).HasName("PK__DonViHan__038427513FC1684E");

            entity.Property(e => e.TenHuyen)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.MaTinhNavigation).WithMany(p => p.DonViHanhChinhHuyen)
                .HasForeignKey(d => d.MaTinh)
                .HasConstraintName("FK__DonViHanh__MaTin__3B75D760");
        });

        modelBuilder.Entity<DonViHanhChinhTinh>(entity =>
        {
            entity.HasKey(e => e.MaTinh).HasName("PK__DonViHan__4CC544802EF29714");

            entity.Property(e => e.TenTinh)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DonViHanhChinhXa>(entity =>
        {
            entity.HasKey(e => e.MaXa).HasName("PK__DonViHan__272520C93AAF8D22");

            entity.Property(e => e.TenXa)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.MaHuyenNavigation).WithMany(p => p.DonViHanhChinhXa)
                .HasForeignKey(d => d.MaHuyen)
                .HasConstraintName("FK__DonViHanh__MaHuy__3E52440B");
        });

        modelBuilder.Entity<HuongDanSuDung>(entity =>
        {
            entity.HasKey(e => e.MaHuongDan).HasName("PK__HuongDan__3D465C430AA61476");

            entity.Property(e => e.NoiDung).HasColumnType("text");
            entity.Property(e => e.TieuDe)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<KhuRung>(entity =>
        {
            entity.HasKey(e => e.MaKhuRung).HasName("PK__KhuRung__9A8EDB104E8BC9D5");

            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenKhuRung)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MaLapDiaNavigation).WithMany(p => p.KhuRung)
                .HasForeignKey(d => d.MaLapDia)
                .HasConstraintName("FK__KhuRung__MaLapDi__7E37BEF6");

            entity.HasOne(d => d.MaLoDatNavigation).WithMany(p => p.KhuRung)
                .HasForeignKey(d => d.MaLoDat)
                .HasConstraintName("FK__KhuRung__MaLoDat__7F2BE32F");

            entity.HasOne(d => d.MaLoaiRungNavigation).WithMany(p => p.KhuRung)
                .HasForeignKey(d => d.MaLoaiRung)
                .HasConstraintName("FK__KhuRung__MaLoaiR__7C4F7684");

            entity.HasOne(d => d.MaNguoiSoHuuNavigation).WithMany(p => p.KhuRung)
                .HasForeignKey(d => d.MaNguoiSoHuu)
                .HasConstraintName("FK__KhuRung__MaNguoi__00200768");

            entity.HasOne(d => d.MaNguonGocNavigation).WithMany(p => p.KhuRung)
                .HasForeignKey(d => d.MaNguonGoc)
                .HasConstraintName("FK__KhuRung__MaNguon__7D439ABD");
        });

        modelBuilder.Entity<LichSuTacDong>(entity =>
        {
            entity.HasKey(e => e.MaTacDong).HasName("PK__LichSuTa__63E49C55ACB743C2");

            entity.Property(e => e.HanhDong)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NoiDung).HasColumnType("text");
            entity.Property(e => e.ThoiGianTacDong)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.LichSuTacDong)
                .HasForeignKey(d => d.MaNguoiDung)
                .HasConstraintName("FK__LichSuTac__MaNgu__5DCAEF64");
        });

        modelBuilder.Entity<LichSuTruyCap>(entity =>
        {
            entity.HasKey(e => e.MaLichSu).HasName("PK__LichSuTr__C443222A1670DCEE");

            entity.Property(e => e.HanhDong)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IPAddress)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ThoiGianTruyCap)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.LichSuTruyCap)
                .HasForeignKey(d => d.MaNguoiDung)
                .HasConstraintName("FK__LichSuTru__MaNgu__59FA5E80");
        });

        modelBuilder.Entity<LoDatRung>(entity =>
        {
            entity.HasKey(e => e.MaLoDat).HasName("PK__LoDatRun__C0D91E7FE0E651C5");

            entity.Property(e => e.ChuSoHuu)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DienTich).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TenLoDat)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ToaDo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MaLapDiaNavigation).WithMany(p => p.LoDatRung)
                .HasForeignKey(d => d.MaLapDia)
                .HasConstraintName("FK__LoDatRung__MaLap__6EF57B66");

            entity.HasOne(d => d.MaLoaiRungNavigation).WithMany(p => p.LoDatRung)
                .HasForeignKey(d => d.MaLoaiRung)
                .HasConstraintName("FK__LoDatRung__MaLoa__6D0D32F4");

            entity.HasOne(d => d.MaNguonGocNavigation).WithMany(p => p.LoDatRung)
                .HasForeignKey(d => d.MaNguonGoc)
                .HasConstraintName("FK__LoDatRung__MaNgu__6E01572D");
        });

        modelBuilder.Entity<LoaiCay>(entity =>
        {
            entity.HasKey(e => e.MaLoaiCay).HasName("PK__LoaiCay__91531ADC729FEE7D");

            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenKhoaHoc)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TenLoaiCay)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<LoaiRung>(entity =>
        {
            entity.HasKey(e => e.MaLoaiRung).HasName("PK__LoaiRung__3E97745E385F8A5B");

            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenLoaiRung)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.MaMenu).HasName("PK__Menu__0EBABE42EF6A8EE2");

            entity.Property(e => e.DuongDan)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.TenMenu)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.Menu)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__Menu__MaTrangTha__5629CD9C");
        });

        modelBuilder.Entity<NguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaNguoiDung).HasName("PK__NguoiDun__C539D76266945E41");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MatKhau)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.NgayTao)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TaiKhoan)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TenNguoiDung)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.NguoiDung)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__NguoiDung__MaTra__4316F928");

            entity.HasOne(d => d.MaXaNavigation).WithMany(p => p.NguoiDung)
                .HasForeignKey(d => d.MaXa)
                .HasConstraintName("FK__NguoiDung__MaXa__4222D4EF");
        });

        modelBuilder.Entity<NguoiDung_Nhom>(entity =>
        {
            entity.HasKey(e => new { e.MaNguoiDung, e.MaNhom }).HasName("PK__NguoiDun__070D2E7E9D3679E4");

            entity.Property(e => e.NgayThamGia)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.NguoiDung_Nhom)
                .HasForeignKey(d => d.MaNguoiDung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NguoiDung__MaNgu__49C3F6B7");

            entity.HasOne(d => d.MaNhomNavigation).WithMany(p => p.NguoiDung_Nhom)
                .HasForeignKey(d => d.MaNhom)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NguoiDung__MaNho__4AB81AF0");

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.NguoiDung_Nhom)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__NguoiDung__MaTra__4BAC3F29");
        });

        modelBuilder.Entity<NguonGocRung>(entity =>
        {
            entity.HasKey(e => e.MaNguonGoc).HasName("PK__NguonGoc__BD3EA836197258A6");

            entity.Property(e => e.TenNguonGoc)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<NhomNguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaNhom).HasName("PK__NhomNguo__234F91CD61A348B2");

            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenNhom)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.NhomNguoiDung)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__NhomNguoi__MaTra__45F365D3");
        });

        modelBuilder.Entity<PhanQuyenNguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaPhanQuyenNguoiDung).HasName("PK__PhanQuye__31EFE567FD6F9768");

            entity.Property(e => e.MaQuyen)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.PhanQuyenNguoiDung)
                .HasForeignKey(d => d.MaNguoiDung)
                .HasConstraintName("FK__PhanQuyen__MaNgu__52593CB8");

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.PhanQuyenNguoiDung)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__PhanQuyen__MaTra__534D60F1");
        });

        modelBuilder.Entity<PhanQuyenNhom>(entity =>
        {
            entity.HasKey(e => e.MaPhanQuyenNhom).HasName("PK__PhanQuye__18BA14B6B0953D60");

            entity.Property(e => e.MaQuyen)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MaNhomNavigation).WithMany(p => p.PhanQuyenNhom)
                .HasForeignKey(d => d.MaNhom)
                .HasConstraintName("FK__PhanQuyen__MaNho__4E88ABD4");

            entity.HasOne(d => d.MaTrangThaiNavigation).WithMany(p => p.PhanQuyenNhom)
                .HasForeignKey(d => d.MaTrangThai)
                .HasConstraintName("FK__PhanQuyen__MaTra__4F7CD00D");
        });

        modelBuilder.Entity<TrangThai>(entity =>
        {
            entity.HasKey(e => e.MaTrangThai).HasName("PK__TrangTha__AADE4138F40228BF");

            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenTrangThai)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TruLuong>(entity =>
        {
            entity.HasKey(e => e.MaTruLuong).HasName("PK__TruLuong__3309B7A008D0CF5C");

            entity.Property(e => e.TheTichGo).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.MaLoDatNavigation).WithMany(p => p.TruLuong)
                .HasForeignKey(d => d.MaLoDat)
                .HasConstraintName("FK__TruLuong__MaLoDa__71D1E811");

            entity.HasOne(d => d.MaLoaiCayNavigation).WithMany(p => p.TruLuong)
                .HasForeignKey(d => d.MaLoaiCay)
                .HasConstraintName("FK__TruLuong__MaLoai__72C60C4A");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}