// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class LichSuTruyCap
{
    public int MaLichSu { get; set; }

    public int? MaNguoiDung { get; set; }

    public DateTime? ThoiGianTruyCap { get; set; }

    public string? IPAddress { get; set; }

    public string? HanhDong { get; set; }

    public virtual NguoiDung? MaNguoiDungNavigation { get; set; }
}