// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class LichSuTacDong
{
    public int MaTacDong { get; set; }

    public int? MaNguoiDung { get; set; }

    public DateTime? ThoiGianTacDong { get; set; }

    public string? HanhDong { get; set; }

    public string? NoiDung { get; set; }

    public virtual NguoiDung? MaNguoiDungNavigation { get; set; }
}