// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class LoaiCay
{
    public int MaLoaiCay { get; set; }

    public string TenLoaiCay { get; set; } = null!;

    public string? TenKhoaHoc { get; set; }

    public bool? LaCayBanDia { get; set; }

    public string? MoTa { get; set; }

    public virtual ICollection<TruLuong> TruLuong { get; set; } = new List<TruLuong>();
}