// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class LoaiRung
{
    public int MaLoaiRung { get; set; }

    public string TenLoaiRung { get; set; } = null!;

    public string? MoTa { get; set; }

    public virtual ICollection<KhuRung> KhuRung { get; set; } = new List<KhuRung>();

    public virtual ICollection<LoDatRung> LoDatRung { get; set; } = new List<LoDatRung>();
}