// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class LoDatRung
{
    public int MaLoDat { get; set; }

    public string TenLoDat { get; set; } = null!;

    public decimal DienTich { get; set; }

    public string? ToaDo { get; set; }

    public int? MaLoaiRung { get; set; }

    public int? MaNguonGoc { get; set; }

    public int? MaLapDia { get; set; }

    public string? ChuSoHuu { get; set; }

    public string? TrangThai { get; set; }

    public virtual ICollection<BienDongRung> BienDongRung { get; set; } = new List<BienDongRung>();

    public virtual ICollection<DienTichChuaCoRung> DienTichChuaCoRung { get; set; } = new List<DienTichChuaCoRung>();

    public virtual ICollection<KhuRung> KhuRung { get; set; } = new List<KhuRung>();

    public virtual DieuKienLapDia? MaLapDiaNavigation { get; set; }

    public virtual LoaiRung? MaLoaiRungNavigation { get; set; }

    public virtual NguonGocRung? MaNguonGocNavigation { get; set; }

    public virtual ICollection<TruLuong> TruLuong { get; set; } = new List<TruLuong>();
}