// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class Menu
{
    public int MaMenu { get; set; }

    public string TenMenu { get; set; } = null!;

    public string? DuongDan { get; set; }

    public int? ThuTu { get; set; }

    public int? MaTrangThai { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }
}