// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class NguonGocRung
{
    public int MaNguonGoc { get; set; }

    public string TenNguonGoc { get; set; } = null!;

    public virtual ICollection<KhuRung> KhuRung { get; set; } = new List<KhuRung>();

    public virtual ICollection<LoDatRung> LoDatRung { get; set; } = new List<LoDatRung>();
}