// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class NguoiDung_Nhom
{
    public int MaNguoiDung { get; set; }

    public int MaNhom { get; set; }

    public DateTime? NgayThamGia { get; set; }

    public int? MaTrangThai { get; set; }

    public virtual NguoiDung MaNguoiDungNavigation { get; set; } = null!;

    public virtual NhomNguoiDung MaNhomNavigation { get; set; } = null!;

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }
}