// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class NguoiDung
{
    public int MaNguoiDung { get; set; }

    public string TenNguoiDung { get; set; } = null!;

    public string TaiKhoan { get; set; } = null!;

    public string MatKhau { get; set; } = null!;

    public string? Email { get; set; }

    public int? MaXa { get; set; }

    public int? MaTrangThai { get; set; }

    public DateTime? NgayTao { get; set; }

    public virtual ICollection<BaoCao> BaoCao { get; set; } = new List<BaoCao>();

    public virtual ICollection<KhuRung> KhuRung { get; set; } = new List<KhuRung>();

    public virtual ICollection<LichSuTacDong> LichSuTacDong { get; set; } = new List<LichSuTacDong>();

    public virtual ICollection<LichSuTruyCap> LichSuTruyCap { get; set; } = new List<LichSuTruyCap>();

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }

    public virtual DonViHanhChinhXa? MaXaNavigation { get; set; }

    public virtual ICollection<NguoiDung_Nhom> NguoiDung_Nhom { get; set; } = new List<NguoiDung_Nhom>();

    public virtual ICollection<PhanQuyenNguoiDung> PhanQuyenNguoiDung { get; set; } = new List<PhanQuyenNguoiDung>();
}