// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class NhomNguoiDung
{
    public int MaNhom { get; set; }

    public string TenNhom { get; set; } = null!;

    public string? MoTa { get; set; }

    public int? MaTrangThai { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }

    public virtual ICollection<NguoiDung_Nhom> NguoiDung_Nhom { get; set; } = new List<NguoiDung_Nhom>();

    public virtual ICollection<PhanQuyenNhom> PhanQuyenNhom { get; set; } = new List<PhanQuyenNhom>();
}