// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class PhanQuyenNhom
{
    public int MaPhanQuyenNhom { get; set; }

    public int? MaNhom { get; set; }

    public string? MaQuyen { get; set; }

    public int? MaTrangThai { get; set; }

    public virtual NhomNguoiDung? MaNhomNavigation { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }
}