// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class QuyHoachRung
{
    public int MaQuyHoach { get; set; }

    public int? MaKhuRung { get; set; }

    public string KyQuyHoach { get; set; } = null!;

    public DateTime? NgayBatDau { get; set; }

    public DateTime? NgayKetThuc { get; set; }

    public string? NoiDungBaoCao { get; set; }

    public string? DuongDanBanDo { get; set; }

    public int? MaNguoiDung { get; set; }

    public int? MaTrangThai { get; set; }

    public virtual KhuRung? MaKhuRungNavigation { get; set; }

    public virtual NguoiDung? MaNguoiDungNavigation { get; set; }

    public virtual TrangThai? MaTrangThaiNavigation { get; set; }
}