// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class TrangThai
{
    public int MaTrangThai { get; set; }

    public string TenTrangThai { get; set; } = null!;

    public string? MoTa { get; set; }

    public virtual ICollection<Menu> Menu { get; set; } = new List<Menu>();

    public virtual ICollection<NguoiDung> NguoiDung { get; set; } = new List<NguoiDung>();

    public virtual ICollection<NguoiDung_Nhom> NguoiDung_Nhom { get; set; } = new List<NguoiDung_Nhom>();

    public virtual ICollection<NhomNguoiDung> NhomNguoiDung { get; set; } = new List<NhomNguoiDung>();

    public virtual ICollection<PhanQuyenNguoiDung> PhanQuyenNguoiDung { get; set; } = new List<PhanQuyenNguoiDung>();

    public virtual ICollection<PhanQuyenNhom> PhanQuyenNhom { get; set; } = new List<PhanQuyenNhom>();

    public virtual ICollection<QuyHoachRung> QuyHoachRung { get; set; } = new List<QuyHoachRung>();
}