// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ForestManagementSystem.Models;

public partial class TruLuong
{
    public int MaTruLuong { get; set; }

    public int? MaLoDat { get; set; }

    public int? MaLoaiCay { get; set; }

    public decimal? TheTichGo { get; set; }

    public int? SoLuongCay { get; set; }

    public DateTime? NgayKiemKe { get; set; }

    public virtual LoDatRung? MaLoDatNavigation { get; set; }

    public virtual LoaiCay? MaLoaiCayNavigation { get; set; }
}